title:              Climate Change on YouTube
description:        ADA 2023 Project (by fADAmily)
author:             fADAmily


# Build settings
#markdown:           kramdown
#paginate:           5
#paginate_path:      "/posts/page:num/"
#plugins:
#  - jekyll-feed
#  - jekyll-paginate
#  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
